# -*- coding: utf-8 -*-  
from pathlib import Path 
path = Path('Source/P_MA/Private/Player/MAPlayerCharacter.cpp') 
text = path.read_text(encoding='utf-8') 
if 'LoadoutComponent-;' in text and 'BindLoadoutDelegates();' not in text: 
    text = text.replace('LoadoutComponent-;', 'LoadoutComponent-;\n\t\tBindLoadoutDelegates();') 
insert_lines = [ 
'void AMAPlayerCharacter::OnRep_PlayerState()', 
'{', 
'\tSuper::OnRep_PlayerState();', 
'\tBindLoadoutDelegates();', 
'}', 
'', 
'void AMAPlayerCharacter::BindLoadoutDelegates()', 
'{', 
'\tif (!PS)', 
'\t{', 
'\t\treturn;', 
'\t}', 
'', 
'\tif (CachedLoadoutPlayerState == PS)', 
'\t{', 
'\t\treturn;', 
'\t}', 
'', 
'\tif (CachedLoadoutPlayerState)', 
'\t{', 
'\t\tCachedLoadoutPlayerState-;', 
'\t\tCachedLoadoutPlayerState-;', 
'\t}', 
'', 
'\tCachedLoadoutPlayerState = PS;', 
'', 
'\tApplyLoadoutFromPlayerState();', 
'}', 
'', 
'void AMAPlayerCharacter::ApplyLoadoutFromPlayerState()', 
'{', 
'\t{', 
'\t\tHandleLoadoutColorChanged(PS-;', 
'\t\tHandleLoadoutWeaponChanged(PS-;', 
'\t}', 
'}', 
'', 
'{', 
'\tif (!LoadoutComponent)', 
'\t{', 
'\t\treturn;', 
'\t}', 
'', 
'\tif (HasAuthority())', 
'\t{', 
'\t\tLoadoutComponent-, ColorData.EyeData);', 
'\t}', 
'\telse', 
'\t{', 
'\t\tLoadoutComponent-;', 
'\t}', 
'}', 
'', 
'void AMAPlayerCharacter::HandleLoadoutWeaponChanged(FName WeaponId)', 
'{', 
'\tif (!WeaponComponent)', 
'\t{', 
'\t\treturn;', 
'\t}', 
'', 
'\tif (WeaponId.IsNone())', 
'\t{', 
'\t\tWeaponComponent-;', 
'\t\treturn;', 
'\t}', 
'', 
'\tif (!WeaponDataTable)', 
'\t{', 
